global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-consumer'
    static_configs:
      - targets: ['kafka-consumer:8000']
        labels:
          instance: 'kafka-consumer:8000'
          service: 'kafka-consumer'
